export enum message {
  IDNOTCONDITION = '아이디가 조건에 맞지 않습니다.',
  PASSWORDNOTCONDITION = '비밀번호가 조건에 맞지 않습니다.',
  PASSWORDNOTACCORD = '비밀번호가 일치하지 않습니다.',
  SOMETHINGNOTINPUT = '입력되지 않은 값이 있습니다.',
  ALREADYID = '이미존재하는 아이디 입니다.',
  POSSIBLEID = '사용가능한 아이디 입니다.',
  ALREADYEMAIL = '이미존재하는 이메일 입니다.',
  POSSIBLEEMAIL = '사용가능한 이메일 입니다.',
  DUPLICATENOTCHECK = '아이디 또는 이메일 중복체크를 해주세요.',
  SIGNUPSUCCESS = '회원가입에 성공하셨습니다.',
  SIGNINSUCCESS = '로그인에 성공하셨습니다.',
  FINDPASSWORDSUCCESS = '패스워드 변경을 위한 주소를 이메일로 전송하였습니다.',
  EMAILSECRETKEYSUCCESS = '이메일로 QR Code를 재발급 받을 수 있는 주소를 전송하였습니다.',
}
