# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DaDaIkSeon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DaDaIkSeon
  pod 'SwiftLint'
  pod 'SwiftOTP'

  target 'DaDaIkSeonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DaDaIkSeonUITests' do
    # Pods for testing
  end

end
